version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  go-client:
    build: 
      context: ./go_client_scrape_target/
    ports:
      - "9200:9200"
      
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/var/lib/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring